name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

env:
  NODE_VERSION: '20'  # Set Node.js version as an environment variable

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest version of checkout action

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3  # Use the latest version of setup-node action
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci  # Use 'ci' instead of 'install' for more reliable CI builds

    - name: Debug Information  # This step helps in troubleshooting
      run: |
        echo "Node version:"
        node --version
        echo "NPM version:"
        npm --version
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "package.json content:"
        cat package.json

    - name: Build project
      run: npm run build  # Make sure this script is defined in your package.json

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r  # Zip everything, adjust if your build output is in a specific directory

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./release.zip

    - name: Clean up artifact
      run: rm
