name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

env:
  NODE_VERSION: '20'  # Set Node.js version as an environment variable

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: ${{ env.NODE_VERSION }}  # Try setting Node version here

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Debug Information
      run: |
        echo "Node version:"
        node --version
        echo "NPM version:"
        npm --version
        echo "package.json content:"
        cat package.json
        echo "Directory contents:"
        ls -la

    - name: Build project
      run: |
        echo "Running build command..."
        npm run build
      env:
        CI: true

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./release.zip

    - name: Clean up artifact
      run: rm release.zip

    - name: Report Status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "Deployment successful! Visit your app at https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        else
          echo "Deployment failed. Please check the logs above for errors."
        fi
