name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

env:
  NODE_VERSION: '20'  # Set Node.js version as an environment variable

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Debug Environment
      run: |
        echo "PATH:"
        echo $PATH
        echo "All Environment Variables:"
        env
        echo "Node executable:"
        which node
        echo "NPM executable:"
        which npm

    - name: Install dependencies
      run: npm ci

    - name: Inspect package.json and build script
      run: |
        echo "package.json content:"
        cat package.json
        echo "Build script:"
        npm run build --dry-run

    - name: Build project (verbose)
      run: |
        echo "Extracting build command..."
        BUILD_CMD=$(node -p "require('./package.json').scripts.build")
        echo "Build command is: $BUILD_CMD"
        echo "Running build command..."
        $BUILD_CMD
        echo "Build command exited with code $?"

    - name: Zip artifact for deployment
      if: success()
      run: zip release.zip ./* -r

    - name: Deploy to Azure Web App
      if: success()
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./release.zip

    - name: Clean up artifact
      if: always()
      run: rm -f release.zip

    - name: Report Status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "Deployment successful! Visit your app at https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        else
          echo "Deployment failed. Please check the logs above for errors."
        fi
